import { PropsWithChildren } from "react";
import styles from "./styles.module.scss";

import {
  AiOutlineDashboard,
  AiOutlineClockCircle,
  AiOutlineInbox,
  AiOutlineCalendar,
  AiOutlineRise,
  AiOutlineSetting,
} from "react-icons/ai";

import Head from "next/head";
import LeftNavbar from "../left-navbar";
import LeftNavItem from "../left-navbar/left-nav-item";
import Topnavbar from "../top-navbar";

interface Props {}

const Layout: React.FC<PropsWithChildren<Props>> = ({ children }) => {
  const renderRoutes = () => {
    const routes = [
      { text: "Home", link: "/", icon: <AiOutlineDashboard /> },
      {
        text: "Time Management",
        link: "/time-management",
        icon: <AiOutlineClockCircle />,
      },
      { text: "Inbox", link: "/inbox", icon: <AiOutlineInbox /> },
      { text: "Calendar", link: "/calendar", icon: <AiOutlineCalendar /> },
      { text: "Analytics", link: "/analytics", icon: <AiOutlineRise /> },
      { text: "Settings", link: "/settings", icon: <AiOutlineSetting /> },
    ];

    return routes.map(({ text, link, icon }) => (
      <LeftNavItem text={text} link={link} icon={icon} key={link} />
    ));
  };

  return (
    <div className={styles.layout}>
      <Head>
        <title>Course Paper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Topnavbar />

      <LeftNavbar renderRoutes={renderRoutes} />

      <main className={styles.main}>{children}</main>
    </div>
  );
};

export default Layout;
